query Products {
    products {
        data {
            id,
            attributes {
                age,
                name,
                createdAt,
                price,
                post_karma,
                description,
                total_karma,
                comment_karma
            }
        }
    }
}